using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LLVM.LLVM_Structures
{
    public enum OpCode
    {
        Ret = 1,
        Br,
        Switch,
        IndirectBr,
        Invoke,
        Unreachable,
        CallBr,
        FNeg,
        Add,
        FAdd,
        Sub,
        FSub,
        Mul,
        FMul,
        UDiv,
        SDiv,
        FDiv,
        URem,
        SRem,
        FRem,
        Shl,
        LShr,
        AShr,
        And,
        Or,
        Xor,
        Alloca,
        Load,
        Store,
        GetElementPtr,
        Trunc,
        ZExt,
        SExt,
        FPToUI,
        FPToSI,
        UIToFP,
        SIToFP,
        FPTrunc,
        FPExt,
        PtrToInt,
        IntToPtr,
        BitCast,
        AddrSpaceCast,
        ICmp,
        FCmp,
        PHI,
        Call,
        Select,
        UserOp1,
        UserOp2,
        VAArg,
        ExtractElement,
        InsertElement,
        ShuffleVector,
        ExtractValue,
        InsertValue,
        Freeze,
        Fence,
        AtomicCmpXchg,
        AtomicRMW,
        Resume,
        LandingPad,
        CleanupRet,
        CatchRet,
        CatchPad,
        CleanupPad,
        CatchSwitch
    }
}
